/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JavaCommandFrame.java
 *
 * Created on Mar 18, 2010, 7:34:13 PM
 */
package abhishekjava.lang;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;

/**
 *
 * @author Abhishek
 */
public class JavaCommandFrame extends javax.swing.JFrame {

	 /** Creates new form JavaCommandFrame */
	 public JavaCommandFrame() {
			initComponents();
			InputStream inStream = new InputStream() {

				 @Override
				 public int read() throws IOException {
						return (int) OutputArea.getText().charAt(OutputArea.getText().length() - 1);
				 }
			};
			System.setIn(inStream);
			PrintStream outStream = new PrintStream(new OutputStream() {

				 @Override
				 public void write(int b) throws IOException {
						OutputArea.setText(OutputArea.getText() + ((char) b));
				 }
			});
			System.setOut(outStream);
	 }

	 /** This method is called from within the constructor to
	  * initialize the form.
	  * WARNING: Do NOT modify this code. The content of this method is
	  * always regenerated by the Form Editor.
	  */
	 @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      OutputArea = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      OutputArea.setColumns(20);
      OutputArea.setRows(5);
      jScrollPane1.setViewportView(OutputArea);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

	 /**
	  * @param args the command line arguments
	  */
	 public static void main(String args[]) {
			java.awt.EventQueue.invokeLater(new Runnable() {

				 public void run() {
						new JavaCommandFrame().setVisible(true);
				 }
			});
			System.out.println("OK");
	 }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextArea OutputArea;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables
}
